- hosts: all
  vars:
    docker_apt_release_channel: "edge"
    terraform_version: "0.11.7"
    terraform_sha256sum: "6b8ce67647a59b2a3f70199c304abca0ddec0e49fd060944c26f666298e23418"
  roles:
    - docker
    - gce_cli
    - aws_cli
    # - azure_cli
    - helm
    - golang
    - nodejs
    - fail2ban
    - terraform
  tasks:
    - name: Install apt packages
      package:
        name: "{{item}}"
        state: present
      with_items:
        - zip
        - jq
        - ncdu
        - xmlstarlet
        - htop
        - ioping
        - iotop
        - dnsutils
        - cowsay

    - name: Install npm modules
      npm:
        name: "{{item}}"
        state: present
        global: yes
      with_items:
        - "@angular/cli"
